// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_american_airborne_winter");
	character\_utility::attachFromArray(xmodelalias\head_allied::main());

	self setViewmodel("xmodel/viewmodel_hands_uswinter");
	
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/playerbody_american_airborne_winter");
	character\_utility::precacheModelArray(xmodelalias\head_allied::main());
	
	precacheModel("xmodel/viewmodel_hands_uswinter");
	
}
